// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    post_id,
    parent_id,
    user_id,
    reply_to_user_id,
    content
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, post_id, parent_id, user_id, reply_to_user_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	PostID        int64         `json:"post_id"`
	ParentID      sql.NullInt64 `json:"parent_id"`
	UserID        int64         `json:"user_id"`
	ReplyToUserID sql.NullInt64 `json:"reply_to_user_id"`
	Content       string        `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comments, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.PostID,
		arg.ParentID,
		arg.UserID,
		arg.ReplyToUserID,
		arg.Content,
	)
	var i Comments
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.UserID,
		&i.ReplyToUserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, post_id, parent_id, user_id, reply_to_user_id, content, created_at, updated_at
FROM comments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comments, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comments
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.UserID,
		&i.ReplyToUserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentsByPost = `-- name: GetCommentsByPost :many
SELECT id, post_id, parent_id, user_id, reply_to_user_id, content, created_at, updated_at
FROM comments
WHERE post_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCommentsByPost(ctx context.Context, postID int64) ([]Comments, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comments{}
	for rows.Next() {
		var i Comments
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.UserID,
			&i.ReplyToUserID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET
    content = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, post_id, parent_id, user_id, reply_to_user_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comments, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Content)
	var i Comments
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.UserID,
		&i.ReplyToUserID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
