// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (
    conversation_id,
    user_id
)
VALUES ($1, $2)
`

type AddConversationMemberParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    is_group,
    group_owner_id,
    group_name
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, is_group, group_owner_id, group_name, group_avatar, last_message_id, last_message_at, created_at, updated_at, conversation_type
`

type CreateConversationParams struct {
	IsGroup      bool           `json:"is_group"`
	GroupOwnerID sql.NullInt64  `json:"group_owner_id"`
	GroupName    sql.NullString `json:"group_name"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversations, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.IsGroup, arg.GroupOwnerID, arg.GroupName)
	var i Conversations
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.GroupOwnerID,
		&i.GroupName,
		&i.GroupAvatar,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConversationType,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, is_group, group_owner_id, group_name, group_avatar, last_message_id, last_message_at, created_at, updated_at, conversation_type
FROM conversations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConversationByID(ctx context.Context, id int64) (Conversations, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversations
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.GroupOwnerID,
		&i.GroupName,
		&i.GroupAvatar,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConversationType,
	)
	return i, err
}

const getConversationByMembers = `-- name: GetConversationByMembers :one
SELECT c.id, c.is_group, c.group_owner_id, c.group_name, c.group_avatar, c.last_message_id, c.last_message_at, c.created_at, c.updated_at, c.conversation_type
FROM conversations c
JOIN conversation_members cm1 ON cm1.conversation_id = c.id
JOIN conversation_members cm2 ON cm2.conversation_id = c.id
WHERE cm1.user_id = $1
  AND cm2.user_id = $2
  AND c.is_group = FALSE
LIMIT 1
`

type GetConversationByMembersParams struct {
	UserID   int64 `json:"user_id"`
	UserID_2 int64 `json:"user_id_2"`
}

func (q *Queries) GetConversationByMembers(ctx context.Context, arg GetConversationByMembersParams) (Conversations, error) {
	row := q.db.QueryRowContext(ctx, getConversationByMembers, arg.UserID, arg.UserID_2)
	var i Conversations
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.GroupOwnerID,
		&i.GroupName,
		&i.GroupAvatar,
		&i.LastMessageID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConversationType,
	)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT u.id, u.email, u.name, u.password_hash, u.role, u.bio, u.avatar, u.cover_photo, u.birthdate, u.phone_number, u.is_active, u.created_at, u.updated_at
FROM users u
JOIN conversation_members cm
    ON cm.user_id = u.id
WHERE cm.conversation_id = $1
ORDER BY u.name
`

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID int64) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Bio,
			&i.Avatar,
			&i.CoverPhoto,
			&i.Birthdate,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT c.id, c.is_group, c.group_owner_id, c.group_name, c.group_avatar, c.last_message_id, c.last_message_at, c.created_at, c.updated_at, c.conversation_type
FROM conversations c
JOIN conversation_members cm
    ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.last_message_at DESC NULLS LAST
`

func (q *Queries) GetUserConversations(ctx context.Context, userID int64) ([]Conversations, error) {
	rows, err := q.db.QueryContext(ctx, getUserConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversations{}
	for rows.Next() {
		var i Conversations
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.GroupOwnerID,
			&i.GroupName,
			&i.GroupAvatar,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConversationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE FROM conversation_members
WHERE conversation_id = $1
  AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const updateConversationLastMessage = `-- name: UpdateConversationLastMessage :exec
UPDATE conversations
SET
    last_message_id = $2,
    last_message_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateConversationLastMessageParams struct {
	ID            int64         `json:"id"`
	LastMessageID sql.NullInt64 `json:"last_message_id"`
	LastMessageAt sql.NullTime  `json:"last_message_at"`
}

func (q *Queries) UpdateConversationLastMessage(ctx context.Context, arg UpdateConversationLastMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationLastMessage, arg.ID, arg.LastMessageID, arg.LastMessageAt)
	return err
}
