// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friendships.sql

package db

import (
	"context"
)

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (
    user_id,
    friend_id
)
VALUES ($1, $2)
`

type CreateFriendshipParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_id = $1
  AND friend_id = $2
`

type DeleteFriendshipParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getFriends = `-- name: GetFriends :many
SELECT u.id, u.email, u.name, u.password_hash, u.role, u.bio, u.avatar, u.cover_photo, u.birthdate, u.phone_number, u.is_active, u.created_at, u.updated_at
FROM users u
JOIN friendships f
    ON f.friend_id = u.id
WHERE f.user_id = $1
  AND u.is_active = TRUE
ORDER BY u.name
`

func (q *Queries) GetFriends(ctx context.Context, userID int64) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Bio,
			&i.Avatar,
			&i.CoverPhoto,
			&i.Birthdate,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFriend = `-- name: IsFriend :one
SELECT EXISTS (
    SELECT 1
    FROM friendships
    WHERE user_id = $1
      AND friend_id = $2
) AS is_friend
`

type IsFriendParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) IsFriend(ctx context.Context, arg IsFriendParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFriend, arg.UserID, arg.FriendID)
	var is_friend bool
	err := row.Scan(&is_friend)
	return is_friend, err
}
