// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friend.request.sql

package db

import (
	"context"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friend_requests
SET
    status = 'accept',
    updated_at = NOW()
WHERE id = $1
RETURNING id, sender_id, receiver_id, status, created_at, updated_at
`

func (q *Queries) AcceptFriendRequest(ctx context.Context, id int64) (FriendRequests, error) {
	row := q.db.QueryRowContext(ctx, acceptFriendRequest, id)
	var i FriendRequests
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friend_requests (
    sender_id,
    receiver_id
)
VALUES (
    $1,
    $2
)
RETURNING id, sender_id, receiver_id, status, created_at, updated_at
`

type CreateFriendRequestParams struct {
	SenderID   int64 `json:"sender_id"`
	ReceiverID int64 `json:"receiver_id"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequests, error) {
	row := q.db.QueryRowContext(ctx, createFriendRequest, arg.SenderID, arg.ReceiverID)
	var i FriendRequests
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friend_requests
WHERE id = $1
`

func (q *Queries) DeleteFriendRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, id)
	return err
}

const getFriendRequestByID = `-- name: GetFriendRequestByID :one
SELECT id, sender_id, receiver_id, status, created_at, updated_at
FROM friend_requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFriendRequestByID(ctx context.Context, id int64) (FriendRequests, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequestByID, id)
	var i FriendRequests
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingFriendRequest = `-- name: GetPendingFriendRequest :one
SELECT id, sender_id, receiver_id, status, created_at, updated_at
FROM friend_requests
WHERE sender_id = $1
  AND receiver_id = $2
  AND status = 'pending'
LIMIT 1
`

type GetPendingFriendRequestParams struct {
	SenderID   int64 `json:"sender_id"`
	ReceiverID int64 `json:"receiver_id"`
}

func (q *Queries) GetPendingFriendRequest(ctx context.Context, arg GetPendingFriendRequestParams) (FriendRequests, error) {
	row := q.db.QueryRowContext(ctx, getPendingFriendRequest, arg.SenderID, arg.ReceiverID)
	var i FriendRequests
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectFriendRequest = `-- name: RejectFriendRequest :one
UPDATE friend_requests
SET
    status = 'reject',
    updated_at = NOW()
WHERE id = $1
RETURNING id, sender_id, receiver_id, status, created_at, updated_at
`

func (q *Queries) RejectFriendRequest(ctx context.Context, id int64) (FriendRequests, error) {
	row := q.db.QueryRowContext(ctx, rejectFriendRequest, id)
	var i FriendRequests
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
