// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.read.sql

package db

import (
	"context"
)

const hasUserSeenMessage = `-- name: HasUserSeenMessage :one
SELECT EXISTS (
    SELECT 1
    FROM message_reads
    WHERE message_id = $1
      AND user_id = $2
) AS seen
`

type HasUserSeenMessageParams struct {
	MessageID int64 `json:"message_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) HasUserSeenMessage(ctx context.Context, arg HasUserSeenMessageParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUserSeenMessage, arg.MessageID, arg.UserID)
	var seen bool
	err := row.Scan(&seen)
	return seen, err
}

const markMessageAsSeen = `-- name: MarkMessageAsSeen :exec
INSERT INTO message_reads (
    message_id,
    user_id
)
VALUES ($1, $2)
ON CONFLICT (message_id, user_id)
DO NOTHING
`

type MarkMessageAsSeenParams struct {
	MessageID int64 `json:"message_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) MarkMessageAsSeen(ctx context.Context, arg MarkMessageAsSeenParams) error {
	_, err := q.db.ExecContext(ctx, markMessageAsSeen, arg.MessageID, arg.UserID)
	return err
}
