// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id,
    sender_id,
    text,
    media_files
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, conversation_id, sender_id, text, media_files, is_deleted, created_at, updated_at
`

type CreateMessageParams struct {
	ConversationID int64           `json:"conversation_id"`
	SenderID       int64           `json:"sender_id"`
	Text           sql.NullString  `json:"text"`
	MediaFiles     json.RawMessage `json:"media_files"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Messages, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Text,
		arg.MediaFiles,
	)
	var i Messages
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Text,
		&i.MediaFiles,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT id, conversation_id, sender_id, text, media_files, is_deleted, created_at, updated_at
FROM messages
WHERE conversation_id = $1
  AND is_deleted = FALSE
ORDER BY created_at DESC
LIMIT $2
`

type GetConversationMessagesParams struct {
	ConversationID int64 `json:"conversation_id"`
	Limit          int32 `json:"limit"`
}

func (q *Queries) GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]Messages, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Messages{}
	for rows.Next() {
		var i Messages
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Text,
			&i.MediaFiles,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, sender_id, text, media_files, is_deleted, created_at, updated_at
FROM messages
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (Messages, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Messages
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Text,
		&i.MediaFiles,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages
SET
    is_deleted = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteMessage, id)
	return err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET
    text = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, conversation_id, sender_id, text, media_files, is_deleted, created_at, updated_at
`

type UpdateMessageParams struct {
	ID   int64          `json:"id"`
	Text sql.NullString `json:"text"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Messages, error) {
	row := q.db.QueryRowContext(ctx, updateMessage, arg.ID, arg.Text)
	var i Messages
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Text,
		&i.MediaFiles,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
