// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ConversationType string

const (
	ConversationTypeDirect  ConversationType = "direct"
	ConversationTypeGroup   ConversationType = "group"
	ConversationTypeChannel ConversationType = "channel"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType `json:"conversation_type"`
	Valid            bool             `json:"valid"` // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type FriendRequestStatus string

const (
	FriendRequestStatusPending FriendRequestStatus = "pending"
	FriendRequestStatusAccept  FriendRequestStatus = "accept"
	FriendRequestStatusReject  FriendRequestStatus = "reject"
)

func (e *FriendRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendRequestStatus(s)
	case string:
		*e = FriendRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendRequestStatus: %T", src)
	}
	return nil
}

type NullFriendRequestStatus struct {
	FriendRequestStatus FriendRequestStatus `json:"friend_request_status"`
	Valid               bool                `json:"valid"` // Valid is true if FriendRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendRequestStatus), nil
}

type NotificationType string

const (
	NotificationTypeFriendRequest NotificationType = "friend_request"
	NotificationTypeReaction      NotificationType = "reaction"
	NotificationTypeComment       NotificationType = "comment"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type PostPrivacy string

const (
	PostPrivacyPublic  PostPrivacy = "public"
	PostPrivacyPrivate PostPrivacy = "private"
	PostPrivacyFriends PostPrivacy = "friends"
)

func (e *PostPrivacy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostPrivacy(s)
	case string:
		*e = PostPrivacy(s)
	default:
		return fmt.Errorf("unsupported scan type for PostPrivacy: %T", src)
	}
	return nil
}

type NullPostPrivacy struct {
	PostPrivacy PostPrivacy `json:"post_privacy"`
	Valid       bool        `json:"valid"` // Valid is true if PostPrivacy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostPrivacy) Scan(value interface{}) error {
	if value == nil {
		ns.PostPrivacy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostPrivacy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostPrivacy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostPrivacy), nil
}

type ReactionType string

const (
	ReactionTypeLike  ReactionType = "like"
	ReactionTypeWow   ReactionType = "wow"
	ReactionTypeLove  ReactionType = "love"
	ReactionTypeAngry ReactionType = "angry"
	ReactionTypeHaha  ReactionType = "haha"
	ReactionTypeSad   ReactionType = "sad"
)

func (e *ReactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactionType(s)
	case string:
		*e = ReactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactionType: %T", src)
	}
	return nil
}

type NullReactionType struct {
	ReactionType ReactionType `json:"reaction_type"`
	Valid        bool         `json:"valid"` // Valid is true if ReactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactionType) Scan(value interface{}) error {
	if value == nil {
		ns.ReactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactionType), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Comments struct {
	ID            int64         `json:"id"`
	PostID        int64         `json:"post_id"`
	ParentID      sql.NullInt64 `json:"parent_id"`
	UserID        int64         `json:"user_id"`
	ReplyToUserID sql.NullInt64 `json:"reply_to_user_id"`
	Content       string        `json:"content"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type ConversationMembers struct {
	ConversationID int64     `json:"conversation_id"`
	UserID         int64     `json:"user_id"`
	JoinedAt       time.Time `json:"joined_at"`
}

type Conversations struct {
	ID               int64                 `json:"id"`
	IsGroup          bool                  `json:"is_group"`
	GroupOwnerID     sql.NullInt64         `json:"group_owner_id"`
	GroupName        sql.NullString        `json:"group_name"`
	GroupAvatar      pqtype.NullRawMessage `json:"group_avatar"`
	LastMessageID    sql.NullInt64         `json:"last_message_id"`
	LastMessageAt    sql.NullTime          `json:"last_message_at"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
	ConversationType ConversationType      `json:"conversation_type"`
}

type FriendRequests struct {
	ID         int64               `json:"id"`
	SenderID   int64               `json:"sender_id"`
	ReceiverID int64               `json:"receiver_id"`
	Status     FriendRequestStatus `json:"status"`
	CreatedAt  time.Time           `json:"created_at"`
	UpdatedAt  time.Time           `json:"updated_at"`
}

type Friendships struct {
	UserID    int64     `json:"user_id"`
	FriendID  int64     `json:"friend_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MessageReads struct {
	MessageID int64     `json:"message_id"`
	UserID    int64     `json:"user_id"`
	SeenAt    time.Time `json:"seen_at"`
}

type Messages struct {
	ID             int64           `json:"id"`
	ConversationID int64           `json:"conversation_id"`
	SenderID       int64           `json:"sender_id"`
	Text           sql.NullString  `json:"text"`
	MediaFiles     json.RawMessage `json:"media_files"`
	IsDeleted      bool            `json:"is_deleted"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Notifications struct {
	ID         int64            `json:"id"`
	SenderID   int64            `json:"sender_id"`
	ReceiverID int64            `json:"receiver_id"`
	Type       NotificationType `json:"type"`
	Content    string           `json:"content"`
	IsRead     bool             `json:"is_read"`
	LinkToID   sql.NullInt64    `json:"link_to_id"`
	CreatedAt  time.Time        `json:"created_at"`
	UpdatedAt  time.Time        `json:"updated_at"`
}

type Posts struct {
	ID              int64           `json:"id"`
	AuthorID        int64           `json:"author_id"`
	BackgroundColor string          `json:"background_color"`
	Content         string          `json:"content"`
	MediaFiles      json.RawMessage `json:"media_files"`
	LikeCount       int32           `json:"like_count"`
	WowCount        int32           `json:"wow_count"`
	LoveCount       int32           `json:"love_count"`
	AngryCount      int32           `json:"angry_count"`
	HahaCount       int32           `json:"haha_count"`
	SadCount        int32           `json:"sad_count"`
	Privacy         PostPrivacy     `json:"privacy"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Reactions struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	PostID    int64        `json:"post_id"`
	Type      ReactionType `json:"type"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type RefreshTokens struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Users struct {
	ID           int64                 `json:"id"`
	Email        string                `json:"email"`
	Name         string                `json:"name"`
	PasswordHash string                `json:"password_hash"`
	Role         UserRole              `json:"role"`
	Bio          sql.NullString        `json:"bio"`
	Avatar       pqtype.NullRawMessage `json:"avatar"`
	CoverPhoto   pqtype.NullRawMessage `json:"cover_photo"`
	Birthdate    sql.NullTime          `json:"birthdate"`
	PhoneNumber  sql.NullString        `json:"phone_number"`
	IsActive     bool                  `json:"is_active"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}
