// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    sender_id,
    receiver_id,
    type,
    content,
    link_to_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, sender_id, receiver_id, type, content, is_read, link_to_id, created_at, updated_at
`

type CreateNotificationParams struct {
	SenderID   int64            `json:"sender_id"`
	ReceiverID int64            `json:"receiver_id"`
	Type       NotificationType `json:"type"`
	Content    string           `json:"content"`
	LinkToID   sql.NullInt64    `json:"link_to_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notifications, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.SenderID,
		arg.ReceiverID,
		arg.Type,
		arg.Content,
		arg.LinkToID,
	)
	var i Notifications
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Type,
		&i.Content,
		&i.IsRead,
		&i.LinkToID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, sender_id, receiver_id, type, content, is_read, link_to_id, created_at, updated_at
FROM notifications
WHERE receiver_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetUserNotificationsParams struct {
	ReceiverID int64 `json:"receiver_id"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notifications, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotifications, arg.ReceiverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notifications{}
	for rows.Next() {
		var i Notifications
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Type,
			&i.Content,
			&i.IsRead,
			&i.LinkToID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET
    is_read = TRUE,
    updated_at = NOW()
WHERE receiver_id = $1
  AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, receiverID int64) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, receiverID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET
    is_read = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, id)
	return err
}
