// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"encoding/json"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    author_id,
    background_color,
    content,
    media_files,
    privacy
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, author_id, background_color, content, media_files, like_count, wow_count, love_count, angry_count, haha_count, sad_count, privacy, created_at, updated_at
`

type CreatePostParams struct {
	AuthorID        int64           `json:"author_id"`
	BackgroundColor string          `json:"background_color"`
	Content         string          `json:"content"`
	MediaFiles      json.RawMessage `json:"media_files"`
	Privacy         PostPrivacy     `json:"privacy"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.AuthorID,
		arg.BackgroundColor,
		arg.Content,
		arg.MediaFiles,
		arg.Privacy,
	)
	var i Posts
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.BackgroundColor,
		&i.Content,
		&i.MediaFiles,
		&i.LikeCount,
		&i.WowCount,
		&i.LoveCount,
		&i.AngryCount,
		&i.HahaCount,
		&i.SadCount,
		&i.Privacy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getFeedPosts = `-- name: GetFeedPosts :many
SELECT p.id, p.author_id, p.background_color, p.content, p.media_files, p.like_count, p.wow_count, p.love_count, p.angry_count, p.haha_count, p.sad_count, p.privacy, p.created_at, p.updated_at
FROM posts p
WHERE p.author_id IN (
    SELECT f.friend_id FROM friendships f WHERE f.user_id = $1
    UNION
    SELECT f.user_id FROM friendships f WHERE f.friend_id = $1
    UNION
    SELECT $1
)
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type GetFeedPostsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]Posts, error) {
	rows, err := q.db.QueryContext(ctx, getFeedPosts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Posts{}
	for rows.Next() {
		var i Posts
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.BackgroundColor,
			&i.Content,
			&i.MediaFiles,
			&i.LikeCount,
			&i.WowCount,
			&i.LoveCount,
			&i.AngryCount,
			&i.HahaCount,
			&i.SadCount,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, background_color, content, media_files, like_count, wow_count, love_count, angry_count, haha_count, sad_count, privacy, created_at, updated_at
FROM posts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id int64) (Posts, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Posts
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.BackgroundColor,
		&i.Content,
		&i.MediaFiles,
		&i.LikeCount,
		&i.WowCount,
		&i.LoveCount,
		&i.AngryCount,
		&i.HahaCount,
		&i.SadCount,
		&i.Privacy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostsByUser = `-- name: GetPostsByUser :many
SELECT id, author_id, background_color, content, media_files, like_count, wow_count, love_count, angry_count, haha_count, sad_count, privacy, created_at, updated_at
FROM posts
WHERE author_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetPostsByUserParams struct {
	AuthorID int64 `json:"author_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]Posts, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUser, arg.AuthorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Posts{}
	for rows.Next() {
		var i Posts
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.BackgroundColor,
			&i.Content,
			&i.MediaFiles,
			&i.LikeCount,
			&i.WowCount,
			&i.LoveCount,
			&i.AngryCount,
			&i.HahaCount,
			&i.SadCount,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET
    content = $2,
    background_color = $3,
    privacy = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, background_color, content, media_files, like_count, wow_count, love_count, angry_count, haha_count, sad_count, privacy, created_at, updated_at
`

type UpdatePostParams struct {
	ID              int64       `json:"id"`
	Content         string      `json:"content"`
	BackgroundColor string      `json:"background_color"`
	Privacy         PostPrivacy `json:"privacy"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Posts, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.Content,
		arg.BackgroundColor,
		arg.Privacy,
	)
	var i Posts
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.BackgroundColor,
		&i.Content,
		&i.MediaFiles,
		&i.LikeCount,
		&i.WowCount,
		&i.LoveCount,
		&i.AngryCount,
		&i.HahaCount,
		&i.SadCount,
		&i.Privacy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
