// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AcceptFriendRequest(ctx context.Context, id int64) (FriendRequests, error)
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comments, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversations, error)
	CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequests, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Messages, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notifications, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error)
	CreateReaction(ctx context.Context, arg CreateReactionParams) (Reactions, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshTokens, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteAllUserRefreshTokens(ctx context.Context, userID int64) error
	DeleteComment(ctx context.Context, id int64) error
	DeleteFriendRequest(ctx context.Context, id int64) error
	DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error
	DeletePost(ctx context.Context, id int64) error
	DeleteReaction(ctx context.Context, arg DeleteReactionParams) error
	DeleteRefreshToken(ctx context.Context, id int64) error
	GetCommentByID(ctx context.Context, id int64) (Comments, error)
	GetCommentsByPost(ctx context.Context, postID int64) ([]Comments, error)
	GetConversationByID(ctx context.Context, id int64) (Conversations, error)
	GetConversationByMembers(ctx context.Context, arg GetConversationByMembersParams) (Conversations, error)
	GetConversationMembers(ctx context.Context, conversationID int64) ([]Users, error)
	GetConversationMessages(ctx context.Context, arg GetConversationMessagesParams) ([]Messages, error)
	GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]Posts, error)
	GetFriendRequestByID(ctx context.Context, id int64) (FriendRequests, error)
	GetFriends(ctx context.Context, userID int64) ([]Users, error)
	GetMessageByID(ctx context.Context, id int64) (Messages, error)
	GetPendingFriendRequest(ctx context.Context, arg GetPendingFriendRequestParams) (FriendRequests, error)
	GetPostByID(ctx context.Context, id int64) (Posts, error)
	GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]Posts, error)
	GetReaction(ctx context.Context, arg GetReactionParams) (Reactions, error)
	GetRefreshTokenHash(ctx context.Context, userID int64) (RefreshTokens, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id int64) (Users, error)
	GetUserConversations(ctx context.Context, userID int64) ([]Conversations, error)
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notifications, error)
	GetValidRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshTokens, error)
	HasUserSeenMessage(ctx context.Context, arg HasUserSeenMessageParams) (bool, error)
	IsFriend(ctx context.Context, arg IsFriendParams) (bool, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	MarkAllNotificationsAsRead(ctx context.Context, receiverID int64) error
	MarkMessageAsSeen(ctx context.Context, arg MarkMessageAsSeenParams) error
	MarkNotificationAsRead(ctx context.Context, id int64) error
	RejectFriendRequest(ctx context.Context, id int64) (FriendRequests, error)
	RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error
	SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]Users, error)
	SoftDeleteMessage(ctx context.Context, id int64) error
	SoftDeleteUser(ctx context.Context, id int64) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comments, error)
	UpdateConversationLastMessage(ctx context.Context, arg UpdateConversationLastMessageParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Messages, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Posts, error)
	UpdateReaction(ctx context.Context, arg UpdateReactionParams) (Reactions, error)
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (RefreshTokens, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
