// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reaction.sql

package db

import (
	"context"
)

const createReaction = `-- name: CreateReaction :one
INSERT INTO reactions (
    user_id,
    post_id,
    type
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, post_id, type, created_at, updated_at
`

type CreateReactionParams struct {
	UserID int64        `json:"user_id"`
	PostID int64        `json:"post_id"`
	Type   ReactionType `json:"type"`
}

func (q *Queries) CreateReaction(ctx context.Context, arg CreateReactionParams) (Reactions, error) {
	row := q.db.QueryRowContext(ctx, createReaction, arg.UserID, arg.PostID, arg.Type)
	var i Reactions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM reactions
WHERE user_id = $1
  AND post_id = $2
`

type DeleteReactionParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteReaction, arg.UserID, arg.PostID)
	return err
}

const getReaction = `-- name: GetReaction :one
SELECT id, user_id, post_id, type, created_at, updated_at
FROM reactions
WHERE user_id = $1
  AND post_id = $2
LIMIT 1
`

type GetReactionParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) GetReaction(ctx context.Context, arg GetReactionParams) (Reactions, error) {
	row := q.db.QueryRowContext(ctx, getReaction, arg.UserID, arg.PostID)
	var i Reactions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReaction = `-- name: UpdateReaction :one
UPDATE reactions
SET
    type = $3,
    updated_at = NOW()
WHERE user_id = $1
  AND post_id = $2
RETURNING id, user_id, post_id, type, created_at, updated_at
`

type UpdateReactionParams struct {
	UserID int64        `json:"user_id"`
	PostID int64        `json:"post_id"`
	Type   ReactionType `json:"type"`
}

func (q *Queries) UpdateReaction(ctx context.Context, arg UpdateReactionParams) (Reactions, error) {
	row := q.db.QueryRowContext(ctx, updateReaction, arg.UserID, arg.PostID, arg.Type)
	var i Reactions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
