// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    name,
    password_hash
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, email, name, password_hash, role, bio, avatar, cover_photo, birthdate, phone_number, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Bio,
		&i.Avatar,
		&i.CoverPhoto,
		&i.Birthdate,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, role, bio, avatar, cover_photo, birthdate, phone_number, is_active, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Bio,
		&i.Avatar,
		&i.CoverPhoto,
		&i.Birthdate,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, role, bio, avatar, cover_photo, birthdate, phone_number, is_active, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Bio,
		&i.Avatar,
		&i.CoverPhoto,
		&i.Birthdate,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, role, bio, avatar, cover_photo, birthdate, phone_number, is_active, created_at, updated_at
FROM users
WHERE is_active = TRUE
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Bio,
			&i.Avatar,
			&i.CoverPhoto,
			&i.Birthdate,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT id, email, name, password_hash, role, bio, avatar, cover_photo, birthdate, phone_number, is_active, created_at, updated_at
FROM users
WHERE is_active = TRUE
  AND name ILIKE '%' || $1 || '%'
  AND id != $3
ORDER BY name
LIMIT $2
`

type SearchUsersByNameParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	ID      int64          `json:"id"`
}

func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByName, arg.Column1, arg.Limit, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Role,
			&i.Bio,
			&i.Avatar,
			&i.CoverPhoto,
			&i.Birthdate,
			&i.PhoneNumber,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET
    is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    bio = $3,
    birthdate = $4,
    phone_number = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, password_hash, role, bio, avatar, cover_photo, birthdate, phone_number, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Bio         sql.NullString `json:"bio"`
	Birthdate   sql.NullTime   `json:"birthdate"`
	PhoneNumber sql.NullString `json:"phone_number"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.Birthdate,
		arg.PhoneNumber,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Bio,
		&i.Avatar,
		&i.CoverPhoto,
		&i.Birthdate,
		&i.PhoneNumber,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
